### ISSUE TITLE
Discussion: App submission form

### ISSUE THREAD

**Issue by Ricardo-Silva91** [ipfs/awesome-ipfs#366]
Hello! I'm opening this issue so we can discuss the possible addition of an in-site form for people to add their app to the grid.
I'll open another issue to discuss the contents of the form (#367), this thread is for discussing the following approach (and other new approaches as they appear 😌).
When a user submits a new app through the form, it would invoke a lambda function (perhaps in cloudflare), that would create a new commit with the form information.
Now, this commit can go one of two ways:
 1. it could be a commit to master, with an 'approved' variable set as `false`. The reason for this is so that [forestry.io](https://forestry.io/) reviewers can see preview and edit/fix it easier, before setting 'approve' to `true` or just deleting it.  Still, committing directly to master could lead to a lot of problems 😅 (and with many submissions, de forestry environment can also become hard to navigate 🤔).
 2. the commit would be in a new branch which is used for a PR to master. This is safer but the review process would become exclusive to Github, so Forestry only editors would be forced to review it in a much less comfortable way (unless we add a 'no-content' review step so that someone else can just check the validity of the change and merge it with the `false` 'approved' flag. Forestry editors can look at the content itself later, but this seems like a hassle 😅)

Once again all new ideas are welcome 🙏

**Comment by Ricardo-Silva91** [comment]
@autonome , please @ anybody you think might want to intervene 😊

**Comment by jessicaschilling** [comment]
@andrew, you might be the most relevant person to give some feedback on this one.

**Comment by andrew** [comment]
@Ricardo-Silva91 both options seem to have some significant drawbacks, I'd suggest sticking closer to GitHub reviews to avoid extra complexity and dependencies on extra systems.

**Comment by jessicaschilling** [comment]
I don't think we have a need for "friendly" (non-GH) means of approving requests - but we would benefit from a way of submitting them that doesn't require the submitter to make a code PR (aka a web form). @autonome, can you confirm? Am I missing something here? Thanks!

**Comment by autonome** [comment]
I defer to @jessicaschilling. If we need non-GH approval, we can layer on later.

**Comment by jessicaschilling** [comment]
Thinking that option 2 above is the best way to go. AFAIK the purpose of this exercise is to give folks who aren't so GitHub-savvy (or who just don't want a GH account - say, a project's PR person) the ability to add a project to Awesome IPFS. Anyone on the core team end who's likely to be evaluating and approving a submission will already be pretty heavily into our GitHub ecosystem, so I don't see a need for Forestry-only editors for this site.

That said - generating a staging link for the result of a Forestry-submitted PR would be extremely useful. That way, an approver doesn't need to bring down the PR and build locally in order to make sure it looks OK visually. But that can just be part of the overall CI for the site.

Sound good to everyone?

**Comment by jessicaschilling** [comment]
Quick note for @Ricardo-Silva91: Please note that this repo's README.md also includes a list of all the apps/articles/etc that appear on the Awesome IFPS website. Please make sure that your form workflow accounts for updating that list, too. 😊

**Comment by 2color** [comment]
Closing this in an effort to reboot this list while keeping the maintainer overhead as low as possible while still making sure the list is awesome! 

See https://github.com/ipfs/awesome-ipfs/pull/478 for more info
