### ISSUE TITLE
Add hiloader.org to Apps section

### ISSUE THREAD

**Issue by noxonsu** [ipfs/awesome-ipfs#70]
* [HiLoader.exe](http://hiloader.org) - An free tool for sharing files via IPFS with "social locker" feature

**Comment by VictorBjelkholm** [comment]
@noxonsu is there a source available somewhere? Kind of scared of running binaries without any way of checking it out first.

**Comment by noxonsu** [comment]
Hi! sure https://github.com/noxonsu/hiloader 
Binary file created via electron.atom.io + ipfs.exe

**Comment by noxonsu** [comment]
any updates? Can we add link to github repo instead website?

**Comment by RichardLitt** [comment]
Why not both? :)

**Comment by noxonsu** [comment]
Let's both

2016-12-06 1:35 GMT+10:00 Richard Littauer <notifications@github.com>:

**Comment by RichardLitt** [comment]
@VictorBjelkholm What do you think?

**Comment by VictorBjelkholm** [comment]
@RichardLitt @noxonsu Did a quick review of what I could see

* If it's open source, I think it should link to the source somewhere on the homepage, right now you can't find the source without knowing the Github repository. However, my opinion, not something that would effect the *awesomeness* of this.
* The ipfs program in the source is a binary blob in the source repository, is there a reason why it can't included a different way? There is other ways of including ipfs in electron, take a look at how [https://github.com/haadcode/orbit](orbit) deals with it
* Webpage (http://hiloader.org/) links to https://ipfs.io/ipfs/QmZRDSfDBThc1Zt85QkYpNMzZrJLA1XsDkaSjGNqjzc6Jd which in his turn links to the "secret" file when clicking on "Download". That file doesn't seem to be available anymore
* Is there something that stops people from just sharing the secret file's hash instead of the pages hash? In that case, it feels like the promise of the application can be very easily broken

**Comment by RichardLitt** [comment]
@noxonsu I opened some issues. Just took a look now. I think this is close; when those are closed, I think this will be pretty awesome. For now, I would fix the issues mentioned there. :)

**Comment by RichardLitt** [comment]
@noxonsu Closing this for now. Ping again when those issues are closed!

**Comment by noxonsu** [comment]
ok!
